---
- name: My test playbook
  hosts: all
  become: true
  tasks:
  - name: creating multiple user
    user:
      name: "{{item}}" 
      state: present
    with_items:
      - suri
      - suman
      - om  
