---
- name: My test playbook
  hosts: all
  become: true
  tasks:
  - name: Installing httpd service
    yum:
     name: httpd
     state: installed
    notify: Start apache2

  handlers:  
  - name: Start apache2
    service: 
     name: httpd
     state: started  
