---
- name: My test playbook
  hosts: all
  become: true

  vars:
    tomcat_version: 9.0.97

  tasks:
  - name: Install java on Redhat
    yum:
     name: java
     state: present

  - name: Download tomcat package
    get_url:
     url: https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
     dest: /opt

  - name: untar apache packages
    unarchive:
     src: /opt/apache-tomcat-{{ tomcat_version }}.tar.gz
     dest: /opt
     remote_src: yes 

  - name: add execution permission on startup.sh
    file:
     path: /opt/apache-tomcat-{{ tomcat_version }}/bin/startup.sh
     mode: 0777

  - name: start tomcat service 
    shell: nohup ./startup.sh
    args: 
     chdir: /opt/apache-tomcat-{{ tomcat_version }}/bin

  

