---
- name: My test playbook
  hosts: all
  become: true
  tasks: 
  - name: stopping httpd service on Redhat systems
    service: 
     name: httpd
     state: stopped
    when: ansible_os_family == "Redhat" 

  - name: uninstalling httpd service on Redhat system
    yum:
     name: httpd
     state: removed
    when: ansible_os_family == "Redhat"

  - name: stopping apache2 service on Debian systems
    service:
     name: apache2
     state: stopped
    when: ansible_os_family == "Debian"

  - name : uninstalling apache2 service on Debian service
    apt:
     name: apache2
     state: removed
    when: ansible_os_family == "Debian"  
